* The Description of a Quantum System
Quantum systems are described by a Hilbert space $\mathbb{H}$. Hilbert spaces are vector 
spaces over the complex numbers $\mathbb{C}$ possessing an inner product that
assigns to every pair of vectors $\varphi_1|\varphi_2\in\mathbb{H}$ a complex
number $\langle \varphi_1,\varphi_2\rangle$.

The vectors $\varphi\in\mathbb{H}$ describe the states a quantum system can
assume. Philosophers adhering to the creed of realism might call this the
/noumenon/ of the quantum system. Speaking more coloquially, it is the 
/underlying reality/ of the quantum system irrespective of whether it qualifies
as a fully fledged noumenon or merely as some sort of phenomenon subject to
sufficient agreement between observers.
* Experiment and Measurement
The state vector description was introduced by physicists to describe the
outcome of experiments on quantum systems in a spirit of empiricism. As a 
consequence, the question of the nature of what the state vector describes
was considered irrelevant. The only thing that matters in this view is its
ability to predict measurements. 

To be more precise, quantum systems can be manipulated to assume a certain 
initial state $\varphi_i$, called the preparation, and after a measurement 
the system will be in a certain final state $\varphi_f$. This sequence of
preparation and measurement is called an experiment. Perhaps it should be
called an elementary experiment because every measurement results in a state
and could be interpreted as a preparation to be followed by another measurement.
For all practical purposes preparations can also be considered measurements
if measurements are defined as an activity causing the quantum system to be in
a definite known state. An experiment would then be a sequence of elementary
experiments or simply a sequence of pairs of measurements.
# A monadic computation

The predictive power of the description lies in the interpretation of the 
squared modulus $\left|\langle\varphi_f|\varphi_i\rangle\right|^2$ of the inner
product of the initial and final vectors as the probability of obtaining 
state $\varphi_f$ by measuring the quantum system after preparing it in state
$\varphi_i$.
* Outcomes and Observables
In an experiment to determine the value of a certain observable quantity of the
quantum system, the vectors $\varphi_f$, $\varphi_i$ are decomposed into a linear
composition of an orthonormal basis $\omega_i$ of the Hilbert space 
$\mathbb{H}$. 

This basis depends on the experiment and constitutes the eigenbasis of a 
hermitian operator $O$ on $\mathbb{H}$ representing the possible measurement
results that the experiment may yield. More precisely, if the system is in
state $\varphi_f$ at the time of measurement and 
$\varphi_f=\sum \langle\varphi_f,\omega_i\rangle\omega_i$ then, after the
measurement, it will be in state $\omega_{i_f}$ with probability 
$\left|\langle\varphi_f,\omega_{i_f}\rangle\right|^2$ and the result of the
measurement is the eigenvalue $\lambda_{i_f}$ to eigenstate $\omega_{i_f}$
of $O$. 

This assumes nondegeneracy of the operator $O$, which means that the 
eigenspaces of $O$ are one-dimensional. Otherwise, the probabilities
change. In case of nondegeneracy, the eigenstates of $O$ are written as
so called ket vectors $|\lambda_i\rangle$ to denote the eigenstate $\omega_i$
with eigenvalue $\lambda_i$.

Thus, in order to ask the universe a question, all that is necessary is to 
decompose its state into an eigenbasis of a Hermitian operator and pick one
of them according to the probabilities involved. The universe will give an
answer no matter how non-sensical the question may seem. Getting 42 as the 
meaning of life is perhaps not as far-fetched as it sounds, unless it is a 
tensorial quantity rather than a scalar.


* Evolution in Time
* Interactions
